-- AlterTable
ALTER TABLE `Tenant`
    ADD COLUMN `maintEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `maintStartWd` INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN `maintStartHm` VARCHAR(5) NOT NULL DEFAULT '22:00',
    ADD COLUMN `maintEndWd` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `maintEndHm` VARCHAR(5) NOT NULL DEFAULT '07:00',
    ADD COLUMN `maintMuteOnly` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `digestEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `digestHour` VARCHAR(5) NOT NULL DEFAULT '08:00',
    ADD COLUMN `digestLastDate` VARCHAR(10) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `JobGroup`
    ADD COLUMN `maintEnabled` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `maintStartWd` INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN `maintStartHm` VARCHAR(5) NOT NULL DEFAULT '22:00',
    ADD COLUMN `maintEndWd` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `maintEndHm` VARCHAR(5) NOT NULL DEFAULT '07:00',
    ADD COLUMN `maintMuteOnly` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `CronJob`
    ADD COLUMN `notes` TEXT NULL,
    ADD COLUMN `ackedAt` DATETIME(3) NULL,
    ADD COLUMN `ackedBy` VARCHAR(190) NULL,
    ADD COLUMN `ackNote` VARCHAR(500) NULL,
    ADD COLUMN `eventMutes` JSON NULL,
    ADD COLUMN `gridViews` JSON NULL;

-- AlterTable
ALTER TABLE `JobRun`
    ADD COLUMN `comment` VARCHAR(500) NULL;
